name: SonarCloud

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    build:
        name: Build and analyze on SonarCloud
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build || echo "No build step defined"

            - name: Run tests
              run: npm test || echo "No tests defined"

            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                  args: >
                      -Dsonar.projectKey=eduardipio03_Projeto-POO -Dsonar.organization=eduardopio03 -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

